// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc;

public interface demoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string errorMessage = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
