// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc;

public interface demoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
